version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: python src/wallet/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A wallet worker --loglevel=info
    depends_on:
      - redis
