# Generated by Django 3.2 on 2024-02-01 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wallets.models.transaction


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(choices=[(wallets.models.transaction.Transaction.Type['DEPOSIT'], 'Deposit'), (wallets.models.transaction.Transaction.Type['WITHDRAW'], 'Withdraw')], max_length=10)),
                ('status', models.CharField(choices=[(wallets.models.transaction.Transaction.Status['PENDING'], 'Pending'), (wallets.models.transaction.Transaction.Status['COMPLETED'], 'Completed'), (wallets.models.transaction.Transaction.Status['CANCELED'], 'Canceled')], default=wallets.models.transaction.Transaction.Status['PENDING'], max_length=10)),
                ('scheduled_timestamp', models.DateTimeField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(choices=[(wallets.models.transaction.Transaction.Type['DEPOSIT'], 'Deposit'), (wallets.models.transaction.Transaction.Type['WITHDRAW'], 'Withdraw')], max_length=10)),
                ('status', models.CharField(choices=[(wallets.models.transaction.Transaction.Status['PENDING'], 'Pending'), (wallets.models.transaction.Transaction.Status['COMPLETED'], 'Completed'), (wallets.models.transaction.Transaction.Status['CANCELED'], 'Canceled')], default=wallets.models.transaction.Transaction.Status['PENDING'], max_length=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
